name: linux

on:
  push:
    branches: [ csi2115-f21 ]
    paths:
      - "linux/**"

env:
  LATEST_COMMIT: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download and unzip
      run:
        wget https://github.com/smblue37/linux/archive/${GITHUB_SHA}
        mv ${GITHUB_SHA}.zip ../../
        cd ../..
        unzip ${GITHUB_SHA}.zip
        cd ./scripts
      
    - name: Build the unzipped source code
      run:
        ./build-linux.sh ../linux-${GITHUB_SHA} tinyconfig
