name: linux

on:
  push:
    branches: [ csi2115-f21 ]
    paths:
      - "linux/**"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download and unzip
      run:
        wget https://github.com/smblue37/linux/archive/33237cef9cc4b294e1fcc6b79b48f4e6e0a19269.zip
        mv 33237cef9cc4b294e1fcc6b79b48f4e6e0a19269.zip ../../
        cd ../..
        unzip 33237cef9cc4b294e1fcc6b79b48f4e6e0a19269.zip
        cd scripts
      
    - name: Build the unzipped source code
      run:
        ./build-linux.sh ../linux-33237cef9cc4b294e1fcc6b79b48f4e6e0a19269 tinyconfig
